# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property.
---
include:
  - board: nice_nano//zmk
    shield: 4c_left nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano//zmk
    shield: 4c_right nice_view
  - board: nice_nano//zmk
    shield: 4c_left oled_i2c_p0p2_swap
    artifact-name: 4c_left_oled_i2c_p0p2_swap
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano//zmk
    shield: 4c_right oled_i2c_p0p2_swap
    artifact-name: 4c_right_oled_i2c_p0p2_swap
  - board: nice_nano//zmk
    shield: 4c_left oled_i2c_p0p2_swap_noinv
    artifact-name: 4c_left_oled_i2c_p0p2_swap_noinv
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano//zmk
    shield: 4c_right oled_i2c_p0p2_swap_noinv
    artifact-name: 4c_right_oled_i2c_p0p2_swap_noinv
  - board: nice_nano//zmk
    shield: 4c_left oled_i2c_p0p2_swap_plain
    artifact-name: 4c_left_oled_i2c_p0p2_swap_plain
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano//zmk
    shield: 4c_right oled_i2c_p0p2_swap_plain
    artifact-name: 4c_right_oled_i2c_p0p2_swap_plain
  - board: nice_nano//zmk
    shield: 4c_left oled_i2c_p0p2_swap_seq
    artifact-name: 4c_left_oled_i2c_p0p2_swap_seq
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano//zmk
    shield: 4c_right oled_i2c_p0p2_swap_seq
    artifact-name: 4c_right_oled_i2c_p0p2_swap_seq
  - board: nice_nano//zmk
    shield: 4c_left oled_i2c_p0p2_swap_seq_remap
    artifact-name: 4c_left_oled_i2c_p0p2_swap_seq_remap
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano//zmk
    shield: 4c_right oled_i2c_p0p2_swap_seq_remap
    artifact-name: 4c_right_oled_i2c_p0p2_swap_seq_remap
  - board: nice_nano//zmk
    shield: settings_reset
